### ISSUE TITLE
Thrive lines

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/rcpchgrowth-python#15]
Interpreting growth velocity for different parameters is difficult because it is different at different ages. Tim Cole has published previously the concept of 'thrive lines' which graph growth velocity centiles for different ages, and suggested they be developed into acetate overlays on top of the papercharts. This could reasonably be imagined well electronically.

**Comment by eatyourpeas** [comment]
Moving this issue into the python package, more its natural home I think.
After some silence I have an initial implementation which has generated this, temporarily graphed using pyplot. I am not sure it is quite what you envisaged and have maybe made a mistake. ![image](https://user-images.githubusercontent.com/1058647/136654118-c0c61839-9acf-449f-9b03-364159b2df11.png)
The code is [here](https://github.com/rcpch/rcpchgrowth-python/blob/thrive-lines/rcpchgrowth/dynamic_growth.py) in the thrive_lines branch in ```dynamic_growth.py```
There are 7 functions that begin on line 129. The main function to focus on is:
```def create_thrive_line(t: list, z1: float, target_centile: float = 5.0):```
where t is a list of ages in intervals > 0 and < 1, z1 is the starting SDS, and the target_centile is the velocity centile requested (equivalent to zv in your example above).
The function increments through the list of ages in steps of 2, using each pair of ages to look up the conditional velocity from the correlation matrix. Where there is no exact match, bilinear interpolation is used. This in turn is plugged into the ```conditional_weight_gain``` equation provided above (and in the paper you provided) to generate a z score which is in turn used to calculate a measurement using the UK-WHO LMS tables. The measurements are collected in a list and plotted against age. The lines are somewhat uneven but the intervals I have used are monthly, and I also used the correlation index in months, rather than the one in weeks, largely to keep things simple in the first instance.
@statist7 let me know if I have understood the process correctly or if I have somehow missed a step.

**Comment by statist7** [comment]
This looks promising. Looking at the code I'm guessing you've used the default 5th velocity centile, and it appears similar to my own 5th centile thrive lines.

You are right that the curves are not smooth, which I think is inevitable, and I smooth them to improve the appearance.

A refinement would be to restrict the thrive lines to within the range of the weight centiles at each age.

A minor inconsistency, you use both target_centile and centile_target in different places.

**Comment by eatyourpeas** [comment]
I have refactored ```target_centile```
The smoothing I see you use a ```spline``` function which must be one of the R libraries. There will undoubtedly be something equivalent in scipy.
I have put in the centile lines and trimmed the thrive lines to be within the margins as you say but they still don't look right:
![image](https://user-images.githubusercontent.com/1058647/137999847-e8100517-4b26-4270-af6e-7d654b0f5f56.png)
EDIT: here they are smoothed:
![image](https://user-images.githubusercontent.com/1058647/138082019-2f1d5732-fb8c-4f15-b5a9-7548a0e3e6d5.png)

**Comment by statist7** [comment]
You are correct, they don't look right. Which velocity centile are they?

Have you got the same time units for the centiles and the correlations?

We probably need a session to discuss - it would need to be 4 November or later for me.

**Comment by eatyourpeas** [comment]
I think maybe I am somewhat closer. These are 5th velocity centiles over one month for weights in boys. They are still not as beautiful as the ones you produced in R, so we should keep that meeting on the 10th if that is ok to tidy. My methodology is tighter this time - I think I missed a step before.
For a collection of lines, the steps I go though are:
1. create a list of ages 0-12 months each a month apart (t)
2. set up a loop that increments a starting SD(z) which is used to create a thrive line on every pass (by calling the ```create_thrive_line``` function); the starting SD value for each line increments by 0.67 SD, starting at -20, ending at +20. Pass into the ```create_thrive_line``` function the list of ages, the sex (boys here), the starting z(z1) and the target_centile (default 5th)
3. Each line returned is smoothed using a natural spline and rendered over the centile chart (this smoothing step currently breaks it, I think because of the nonetypes)

The steps for each thrive line are:
1. Each thrive line starts as an empty list, initialised with the SD passed in from above which forms z1 at t1 (first value in list t).
2. The correlation (r) between the first and second ages (t1 and t2) in list t is found using the correlation matrix
3. z2 is then calculated using r, z1 and the velocity z requested (zv - defaults to -1.644 [5th centile] if not supplied)
4. z2 is then added to the list at t2.
5. The process repeats, stepping through the list of ages, using the current and the next age to calculate the next z, until values for z have been calculated for each age in the list.
6. If any zs are outside of the upper or lower limits of the centile chart these are discarded. 
7. These zs are then converted to weights in the standard way using the LMS tables.
8. The final list of weights and ages is returned above for smoothing and plotting 

Just for my peace of mind, I would be grateful if you could check that these steps are broadly correct.

![image](https://user-images.githubusercontent.com/1058647/138364018-9faf076a-7178-4640-941d-2129c6dc418d.png)

**Comment by statist7** [comment]
Excellent! - that looks really good.

A refinement I developed was getting the thrive lines to stop on, rather than inside, the outer centiles. This way the range of the thrive lines defines the range of normal growth between the 0.4th and 99.6th centiles.

**Comment by eatyourpeas** [comment]
A step closer. Nearly there.
![image](https://user-images.githubusercontent.com/1058647/141698562-c0e57673-29c3-453e-b697-61901489a06c.png)

**Comment by statist7** [comment]
That looks really good. 

Just a couple of queries/comments. Why do the thrive lines (largely) stop at age ~0.8 rather than 1.0?

And I note that the starting z-score values to need extend downwards, to fill in the low triangular region at birth.

**Comment by pacharanero** [comment]
Great stuff @eatyourpeas !

**Comment by eatyourpeas** [comment]
You are right @statist7 that it does not quite work. I will close this now as we have implemented the feature but it is not ready for production yet and still needs work.

**Comment by mbarton** [comment]
Hijacking the old thread to save this forum post where a dev is asking for an API for thrive lines: https://developer.community.nhs.uk/t/apis-for-thrive-line/561
