### ISSUE TITLE
Python Version Upgrade

### ISSUE THREAD

**Issue by pacharanero** [rcpch/rcpchgrowth-python#18]
The `rcpchgrowth` Python package currently requires Python version 3.5 or above and less than 3.9 and was originally engineered to run in Python 3.8.
 
[python_requires='>=3.5, <3.9',](https://github.com/rcpch/rcpchgrowth-python/blob/6bebfe2d4a03cba1843064d4b0365fd3ed68c44c/setup.py#L28)

According to https://devguide.python.org/versions/ we should be looking to move to at least 3.10 if not 3.11 and deprecate some older versions.

PLAN/
* Create a branch for the upgrade
* Upgrade the allowed Python versions in the `rcpchgrowth` package
* Test this locally
* Upgrade [dgc-server](https://github.com/rcpch/digital-growth-charts-server) in a branch accordingly and test locally see related Issue https://github.com/rcpch/digital-growth-charts-server/issues/189
* Push to `prerelease` branch and check deploy successful
* PR and merge to `live`

**Comment by eatyourpeas** [comment]
closed with release 3.2.1
