### ISSUE TITLE
Midparental height calculation

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/rcpchgrowth-python#25]
Currently midparental height simply calculates the average of the corrected heights of both parents (maternal +13cm in a boy, paternal -13cm in a girl) as per the current RCPCH guidance. In fact though, as @statist7 will tell you, this is actually inaccurate as it does not account for the regression to the mean, as per [this paper](https://github.com/rcpch/rcpchgrowth-python/files/14232812/v082p00173.pdf). This is particularly relevant when there are large differences in the heights between parents: [Jada Pinkett Smith and Will Smith](https://www.buzzfeed.com/ehisosifo1/celebrity-couples-height-differences-2021) might be a famous example.

It might be more thorough therefore to include this alternative calculation in the midparental height object in addition to the existing, though is arguably complicated.

**Comment by statist7** [comment]
Thanks @eatyourpeas for flagging my 2000 paper, which I had completely forgotten about!

It needs a height z-score from parent or sibling, so it's more flexible than the midparent height. But it's quite complicated for the API, and not well-known, so I would have thought was of low priority.
