### ISSUE TITLE
height prediction

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/rcpchgrowth-python#26]
There are a number of height prediction methodologies out there. 
If the request contains information about parental heights, the child's height and gestation, bone age, it may be possible to leverage some of these and return them in the `Measurement` class object.

I am not sure how desirable or practical this is but post here for conversation about what might reasonably be added. 

Particularly since this project might be used for research as well as clinical use.

**Comment by statist7** [comment]
You can add sibling height to the list, see #25. It makes sense to allow such data to be recorded, but the mechanics of implementing a particular prediction methodology are complicated and I suggest outside the remit of the dGC.
