### ISSUE TITLE
Synthetic Child Data calculation code

### ISSUE THREAD

**Issue by pacharanero** [rcpch/rcpchgrowth-python#3]
We have found a use-case where a Synthetic Child Data endpoint might be useful - this is in generating some 'plausible' demo data to plot on the Demo React client, for when we're doing a rapid demo to people. 

There will be a button in the React Client which will auto-fill a number of plotted points (may be configurable)

This button will call the Synthetic Child Data API endpoint to get dummy data, then it will plot the points.

There used to be a Fictional Child endpoint so it's been done once. We can probably go back in the Git history and bring that endpoint back, but of course the calculation will now be done in the `rcpchgrowth-python` external package.

## Synthetic Child Data API sketch (based on how it used to work)
* start SDS
* end SDS
* number of points to plot
* randomness - the 'scatter' either side of a straight line between Start and End SDS

## `rcpchgrowth-python` Implementation needs
* a `generate_synthetic_child_data` function to calculate the synthetic child parameters
* `test_synthetic_child_data.py` with some tests
* documentation (at least just a stub) [here](https://github.com/rcpch/digital-growth-charts-documentation/blob/live/docs/products/python-library.md)

**Comment by eatyourpeas** [comment]
I wrote the original fictional child code so am happy to have another go
S

**Comment by eatyourpeas** [comment]
first implementation with a1a011f.
Closing this.
