### ISSUE TITLE
CDC data

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/rcpchgrowth-python#35]
There have been several requests to include other references in the API.
The first is for CDC  (which should really be called US-WHO) since, like the UK, it is a mash-up of US and WHO data. Here the non-disjunction will be at aged 2y - this is much easier since there is a naturally break at this age anyway where children go from being measured lying down (length) to standing up.

**Comment by pacharanero** [comment]
I like the pattern of `us-who` because it does match our previous naming pattern, although we need to be careful that it is just one char away from `uk-who` and thereby could carry a little risk of accidentally connecting to the wrong API path.

It might be safer to go with `cdc-who`, which is visually very different from `uk-who`, and also doesn't upset anyone who uses the CDC data but isn't in the USA. I suspect a lot of smaller countries in the Americas will do this. If we keep it to the **name of the data source** rather than the country of adoption it's possibly cleaner. As well as harder to accidentally mistype, in this case.

**Comment by mbarton** [comment]
[commenting from a quick pairing session Simon did to run me through the rcpchgrowth code this morning]

Which underlying dataset to use when is summarised in the [CDC growth chart FAQ](https://www.cdc.gov/growthcharts/information-for-healthcare-professionals.htm)

![Capture](https://github.com/user-attachments/assets/9eaed9d4-7c89-4780-bdfc-55cf9c93fda7)

**Comment by eatyourpeas** [comment]
@statist7 would love your knowledge here - the CDC-WHO data do not seem to have disjunction between the two datasets at 2y and have changed the decimal age intervals to half-months, meaning that that there is no 2y cutoff, only a 24.5 month cutoff. Have I understood that right? Do you know anything about how they have stitched CDC and WHO together?

**Comment by statist7** [comment]
You are probably right, though I've not looked at how they've implemented WHO. I remember struggling with CDC because it associates LMS values with the mean age for each month rather than an exact age, so it introduces a half-month offset which is very fiddly.

**Comment by eatyourpeas** [comment]
Fiddly, exactly. But actually, even before we look at the half-month thing, I am finding the WHO part of the CDC published data does not match. So for example length in male infants at 0y in the CDC reference should really be the same data as the WHO2006 standard. In the CDC supplied .csv we see the following values:

| L | M | S |
|---|----|---|
| 1.267004226 | 49.98888408 | 0.0531121908 |

However in the WHO2006 standard we get the following

| L | M | S |
|---|----|---|
1 | 49.8842 | 0.03795

What do you think? Is it possible that the US did some kind of manipulation to the underlying WHO LMS values to allow them to match up with their own at 2y? There is no disjunction in the CDC charts between WHO and CDC at 2y - which suggests as much.

Here are the CDC charts for length in boys - as you can see there is no step at 2 y (either due to the way they are measure, or due to the change in the datasets). And if you look carefully, the two charts are not the same:
<img width="721" alt="image" src="https://github.com/user-attachments/assets/a20bbc36-523c-41e7-8e5a-d0b0991ca7c8">
These are the WHO2006 charts for length in boys
<img width="744" alt="image" src="https://github.com/user-attachments/assets/fa30cedf-95b4-4092-a907-993a56bf9322">

**Comment by eatyourpeas** [comment]
Additional observation here:
This is an implementation with the CDC reference from 2 til 20y and WHO standard 0-2y (which is what CDC is described to be). There looks to be a disjunction of nearly 3 centiles difference.
<img width="701" alt="image" src="https://github.com/user-attachments/assets/f4ded602-e966-47c1-8260-fce32b654b52">

**Comment by statist7** [comment]
Yes, they have obviously tweaked the WHO LMS curves to avoid a disjunction. I know that WHO set L to 1 for length, so that's a giveaway. And the S value of 0.053 instead of the WHO 0.038 corresponds to dramatically greater variability in birth length.

Surely this smoothing process is documented somewhere - I've not followed it.

**Comment by eatyourpeas** [comment]
I have found the explainer [here](https://www.cdc.gov/nchs/data/series/sr_11/sr11_246.pdf)
A particularly relevant part:
> *Combining length-for-age and
stature-for-age—* A smooth transition
from the length-for-age to stature-forage chart was required. Analyses of data
from NHANES II and III children
indicated that recumbent length is, on
average, 0.8 cm longer than standing
height (stature). Thus, it is desirable to
have parallel smoothed percentile curves
for length-for-age and stature-for-age
with a difference of 0.8 cm between
length and stature in the overlapping
ages from 24 to 36 months.

Essentially both datasets were smoothed and the value 0.8cm either added or substracted as this was their calculated difference between lying and standing.

The take home is that we cannot swap datasets in and out for the CDC reference, as we do with UK-WHO, but will have to use the WHO(US) version for the infants and then the CDC2000 for the over 2s. I think I have this working now though would value your review of the BMI centiles.

For BMI in 2022 CDC was upgraded to include an 85th percentile (in addition to 90 and 95), but also include a 98, 99, 99.9 and a 99.99th. These correspond to z scores of +2.0, +2.33, +3.09 and +3.72. The underlying data has not changed, only the numbers of lines on the charts.

**Comment by statist7** [comment]
That seems to match almost exactly what WHO did with length. 

I know that they struggle with high BMI centiles in the US. I wrote a paper with David Freedman from CDC about cut-offs based on percentage of the median, which are very complicated - see [https://doi.org/10.1017/s0007114519002046](url)

**Comment by eatyourpeas** [comment]
Thank you this is very good.
This is what I get for including 99, 99.9 and 99.99th centiles calculated in the standard way.
<img width="849" alt="image" src="https://github.com/user-attachments/assets/bd1b6f11-2178-43d9-bb60-6cc3cb1c8c01">
This though is what CDC produced in 2022
<img width="700" alt="image" src="https://github.com/user-attachments/assets/3ed7f771-dd5d-4474-9465-46ca79e54989">

Is this likely a mistake I am making or is there some other approach that CDC may have made to achieve their more beautiful result?

**Comment by statist7** [comment]
Clearly CDC and you have done different things!

I think the high curves are based on multiples of the 95th percentile, and CDC may have made some distributional assumptions to justify labelling them as 98, 99 and 99.9. But I can't remember the details. 

This is David Freedman's field, and you should probably find an explanation of the plot that involves him if you search.

Looking at this reminds me of something quite different but possibly related - the way that WHO handles weight and BMI outside ±3 z-scores. Have we discussed this already? Either way it probably deserves its own issue.

**Comment by eatyourpeas** [comment]
OMG I am so sorry. Perhaps I should do my research a bit more before posting here:
[clear beautifully documented methodology](https://www.cdc.gov/growthcharts/extended-bmi-data-files.htm)

You are right there is a clear explanation as to how it was done: you have to apply a correction (the cumulative distribution function) to the final result  for any values below the 95th centile (or its inverse if above).

The CDC csvs have all the centiles precalculated actually so I shall use these in the package but for our `chart-coordinates` endpoint for cdc I will use this methodology.

**Comment by eatyourpeas** [comment]
And here is the BMI chart for CDC now that I have done it the way D Freedman and colleagues intended
<img width="1057" alt="image" src="https://github.com/user-attachments/assets/ea740ce9-69fe-4903-b722-5491e38f1d79">

**Comment by statist7** [comment]
Looks good!

Sent from my iPhone

On 24 Sep 2024, at 07:08, Simon Chapman ***@***.***> wrote:

﻿

⚠ Caution: External sender


And here is the BMI chart for CDC now that I have done it the way D Freedman and colleagues intended
image.png (view on web)<https://github.com/user-attachments/assets/ea740ce9-69fe-4903-b722-5491e38f1d79>

**Comment by statist7** [comment]
Just noticed. The units for age are (in years) but those for BMI are (kg/m2). Inconsistent!

**Comment by eatyourpeas** [comment]
thank you @statist7 - do you mean to remove the word `in` ? Absolutely - will do!
